const products = [
  {
    id: 35,
    name: "WordPress Pennant",
    slug: "wordpress-pennant",
    permalink: "http://wooapp.local/product/wordpress-pennant/",
    date_created: "2021-06-10T13:37:41",
    date_created_gmt: "2021-06-10T13:37:41",
    date_modified: "2021-06-10T13:38:28",
    date_modified_gmt: "2021-06-10T13:38:28",
    type: "external",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>\n",
    short_description: "<p>This is an external product.</p>\n",
    sku: "wp-pennant",
    price: "11.05",
    regular_price: "11.05",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: false,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: "https://mercantile.wordpress.org/product/wordpress-pennant/",
    button_text: "Buy on the WordPress swag store!",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: {
      length: "",
      width: "",
      height: "",
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      {
        id: 21,
        name: "Decor",
        slug: "decor",
      },
    ],
    tags: [],
    images: [
      {
        id: 58,
        date_created: "2021-06-10T13:38:28",
        date_created_gmt: "2021-06-10T13:38:28",
        date_modified: "2021-06-10T13:38:28",
        date_modified_gmt: "2021-06-10T13:38:28",
        src: "http://wooapp.local/wp-content/uploads/2021/06/pennant-1.jpg",
        name: "pennant-1.jpg",
        alt: "",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>11.05</bdi></span>',
    related_ids: [],
    meta_data: [
      {
        id: 669,
        key: "_wpcom_is_markdown",
        value: "1",
      },
    ],
    stock_status: "instock",
    _links: {
      self: [
        {
          href: "http://wooapp.local/wp-json/wc/v3/products/35",
        },
      ],
      collection: [
        {
          href: "http://wooapp.local/wp-json/wc/v3/products",
        },
      ],
    },
  },
  {
    id: 34,
    name: "Logo Collection",
    slug: "logo-collection",
    permalink: "http://wooapp.local/product/logo-collection/",
    date_created: "2021-06-10T13:37:41",
    date_created_gmt: "2021-06-10T13:37:41",
    date_modified: "2021-06-10T13:38:24",
    date_modified_gmt: "2021-06-10T13:38:24",
    type: "grouped",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>\n",
    short_description: "<p>This is a grouped product.</p>\n",
    sku: "logo-collection",
    price: "18",
    regular_price: "",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: false,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: {
      length: "",
      width: "",
      height: "",
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      {
        id: 16,
        name: "Clothing",
        slug: "clothing",
      },
    ],
    tags: [],
    images: [
      {
        id: 57,
        date_created: "2021-06-10T13:38:23",
        date_created_gmt: "2021-06-10T13:38:23",
        date_modified: "2021-06-10T13:38:23",
        date_modified_gmt: "2021-06-10T13:38:23",
        src: "http://wooapp.local/wp-content/uploads/2021/06/logo-1.jpg",
        name: "logo-1.jpg",
        alt: "",
      },
      {
        id: 56,
        date_created: "2021-06-10T13:38:21",
        date_created_gmt: "2021-06-10T13:38:21",
        date_modified: "2021-06-10T13:38:21",
        date_modified_gmt: "2021-06-10T13:38:21",
        src: "http://wooapp.local/wp-content/uploads/2021/06/beanie-with-logo-1.jpg",
        name: "beanie-with-logo-1.jpg",
        alt: "",
      },
      {
        id: 55,
        date_created: "2021-06-10T13:38:19",
        date_created_gmt: "2021-06-10T13:38:19",
        date_modified: "2021-06-10T13:38:19",
        date_modified_gmt: "2021-06-10T13:38:19",
        src: "http://wooapp.local/wp-content/uploads/2021/06/t-shirt-with-logo-1.jpg",
        name: "t-shirt-with-logo-1.jpg",
        alt: "",
      },
      {
        id: 43,
        date_created: "2021-06-10T13:37:50",
        date_created_gmt: "2021-06-10T13:37:50",
        date_modified: "2021-06-10T13:37:50",
        date_modified_gmt: "2021-06-10T13:37:50",
        src: "http://wooapp.local/wp-content/uploads/2021/06/hoodie-with-logo-2.jpg",
        name: "hoodie-with-logo-2.jpg",
        alt: "",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [14, 15, 16],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>18.00</bdi></span> &ndash; <span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>45.00</bdi></span>',
    related_ids: [],
    meta_data: [
      {
        id: 653,
        key: "_wpcom_is_markdown",
        value: "1",
      },
    ],
    stock_status: "instock",
    _links: {
      self: [
        {
          href: "http://wooapp.local/wp-json/wc/v3/products/34",
        },
      ],
      collection: [
        {
          href: "http://wooapp.local/wp-json/wc/v3/products",
        },
      ],
    },
  },
  {
    id: 33,
    name: "Beanie with Logo",
    slug: "beanie-with-logo",
    permalink: "http://wooapp.local/product/beanie-with-logo/",
    date_created: "2021-06-10T13:37:41",
    date_created_gmt: "2021-06-10T13:37:41",
    date_modified: "2021-06-10T13:38:21",
    date_modified_gmt: "2021-06-10T13:38:21",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>\n",
    short_description: "<p>This is a simple product.</p>\n",
    sku: "Woo-beanie-logo",
    price: "18",
    regular_price: "20",
    sale_price: "18",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: {
      length: "",
      width: "",
      height: "",
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      {
        id: 19,
        name: "Accessories",
        slug: "accessories",
      },
    ],
    tags: [],
    images: [
      {
        id: 56,
        date_created: "2021-06-10T13:38:21",
        date_created_gmt: "2021-06-10T13:38:21",
        date_modified: "2021-06-10T13:38:21",
        date_modified_gmt: "2021-06-10T13:38:21",
        src: "http://wooapp.local/wp-content/uploads/2021/06/beanie-with-logo-1.jpg",
        name: "beanie-with-logo-1.jpg",
        alt: "",
      },
    ],
    attributes: [
      {
        id: 1,
        name: "Color",
        position: 0,
        visible: true,
        variation: false,
        options: ["Red"],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>20.00</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>18.00</bdi></span></ins>',
    related_ids: [18, 16, 19, 17],
    meta_data: [
      {
        id: 643,
        key: "_wpcom_is_markdown",
        value: "1",
      },
    ],
    stock_status: "instock",
    _links: {
      self: [
        {
          href: "http://wooapp.local/wp-json/wc/v3/products/33",
        },
      ],
      collection: [
        {
          href: "http://wooapp.local/wp-json/wc/v3/products",
        },
      ],
    },
  },
  {
    id: 32,
    name: "T-Shirt with Logo",
    slug: "t-shirt-with-logo",
    permalink: "http://wooapp.local/product/t-shirt-with-logo/",
    date_created: "2021-06-10T13:37:41",
    date_created_gmt: "2021-06-10T13:37:41",
    date_modified: "2021-06-10T13:38:19",
    date_modified_gmt: "2021-06-10T13:38:19",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>\n",
    short_description: "<p>This is a simple product.</p>\n",
    sku: "Woo-tshirt-logo",
    price: "18",
    regular_price: "18",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: {
      length: "",
      width: "",
      height: "",
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      {
        id: 17,
        name: "Tshirts",
        slug: "tshirts",
      },
    ],
    tags: [],
    images: [
      {
        id: 55,
        date_created: "2021-06-10T13:38:19",
        date_created_gmt: "2021-06-10T13:38:19",
        date_modified: "2021-06-10T13:38:19",
        date_modified_gmt: "2021-06-10T13:38:19",
        src: "http://wooapp.local/wp-content/uploads/2021/06/t-shirt-with-logo-1.jpg",
        name: "t-shirt-with-logo-1.jpg",
        alt: "",
      },
    ],
    attributes: [
      {
        id: 1,
        name: "Color",
        position: 0,
        visible: true,
        variation: false,
        options: ["Gray"],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>18.00</bdi></span>',
    related_ids: [22, 23, 15, 12],
    meta_data: [
      {
        id: 634,
        key: "_wpcom_is_markdown",
        value: "1",
      },
    ],
    stock_status: "instock",
    _links: {
      self: [
        {
          href: "http://wooapp.local/wp-json/wc/v3/products/32",
        },
      ],
      collection: [
        {
          href: "http://wooapp.local/wp-json/wc/v3/products",
        },
      ],
    },
  },
  {
    id: 25,
    name: "Single",
    slug: "single",
    permalink: "http://wooapp.local/product/single/",
    date_created: "2021-06-10T13:37:39",
    date_created_gmt: "2021-06-10T13:37:39",
    date_modified: "2021-06-10T13:38:16",
    date_modified_gmt: "2021-06-10T13:38:16",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sagittis orci ac odio dictum tincidunt. Donec ut metus leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed luctus, dui eu sagittis sodales, nulla nibh sagittis augue, vel porttitor diam enim non metus. Vestibulum aliquam augue neque. Phasellus tincidunt odio eget ullamcorper efficitur. Cras placerat ut turpis pellentesque vulputate. Nam sed consequat tortor. Curabitur finibus sapien dolor. Ut eleifend tellus nec erat pulvinar dignissim. Nam non arcu purus. Vivamus et massa massa.</p>\n",
    short_description: "<p>This is a simple, virtual product.</p>\n",
    sku: "woo-single",
    price: "2",
    regular_price: "3",
    sale_price: "2",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 0,
    virtual: true,
    downloadable: true,
    downloads: [
      {
        id: "14fb46f4-3b0a-44ff-bf09-6d6696f10540",
        name: "Single",
        file: "https://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2017/08/single.jpg",
      },
    ],
    download_limit: 1,
    download_expiry: 1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: {
      length: "",
      width: "",
      height: "",
    },
    shipping_required: false,
    shipping_taxable: false,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      {
        id: 20,
        name: "Music",
        slug: "music",
      },
    ],
    tags: [],
    images: [
      {
        id: 54,
        date_created: "2021-06-10T13:38:16",
        date_created_gmt: "2021-06-10T13:38:16",
        date_modified: "2021-06-10T13:38:16",
        date_modified_gmt: "2021-06-10T13:38:16",
        src: "http://wooapp.local/wp-content/uploads/2021/06/single-1.jpg",
        name: "single-1.jpg",
        alt: "",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>3.00</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>2.00</bdi></span></ins>',
    related_ids: [24],
    meta_data: [
      {
        id: 573,
        key: "_wpcom_is_markdown",
        value: "1",
      },
    ],
    stock_status: "instock",
    _links: {
      self: [
        {
          href: "http://wooapp.local/wp-json/wc/v3/products/25",
        },
      ],
      collection: [
        {
          href: "http://wooapp.local/wp-json/wc/v3/products",
        },
      ],
    },
  },
  {
    id: 24,
    name: "Album",
    slug: "album",
    permalink: "http://wooapp.local/product/album/",
    date_created: "2021-06-10T13:37:39",
    date_created_gmt: "2021-06-10T13:37:39",
    date_modified: "2021-06-10T13:38:14",
    date_modified_gmt: "2021-06-10T13:38:14",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sagittis orci ac odio dictum tincidunt. Donec ut metus leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed luctus, dui eu sagittis sodales, nulla nibh sagittis augue, vel porttitor diam enim non metus. Vestibulum aliquam augue neque. Phasellus tincidunt odio eget ullamcorper efficitur. Cras placerat ut turpis pellentesque vulputate. Nam sed consequat tortor. Curabitur finibus sapien dolor. Ut eleifend tellus nec erat pulvinar dignissim. Nam non arcu purus. Vivamus et massa massa.</p>\n",
    short_description: "<p>This is a simple, virtual product.</p>\n",
    sku: "woo-album",
    price: "15",
    regular_price: "15",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 0,
    virtual: true,
    downloadable: true,
    downloads: [
      {
        id: "cf38e00f-f332-42b7-b4c7-7f753632abb2",
        name: "Single 1",
        file: "https://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2017/08/single.jpg",
      },
      {
        id: "26c58d94-f31b-44d7-ae31-857aa4209148",
        name: "Single 2",
        file: "https://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2017/08/album.jpg",
      },
    ],
    download_limit: 1,
    download_expiry: 1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: {
      length: "",
      width: "",
      height: "",
    },
    shipping_required: false,
    shipping_taxable: false,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      {
        id: 20,
        name: "Music",
        slug: "music",
      },
    ],
    tags: [],
    images: [
      {
        id: 53,
        date_created: "2021-06-10T13:38:14",
        date_created_gmt: "2021-06-10T13:38:14",
        date_modified: "2021-06-10T13:38:14",
        date_modified_gmt: "2021-06-10T13:38:14",
        src: "http://wooapp.local/wp-content/uploads/2021/06/album-1.jpg",
        name: "album-1.jpg",
        alt: "",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>15.00</bdi></span>',
    related_ids: [25],
    meta_data: [
      {
        id: 564,
        key: "_wpcom_is_markdown",
        value: "1",
      },
    ],
    stock_status: "instock",
    _links: {
      self: [
        {
          href: "http://wooapp.local/wp-json/wc/v3/products/24",
        },
      ],
      collection: [
        {
          href: "http://wooapp.local/wp-json/wc/v3/products",
        },
      ],
    },
  },
  {
    id: 23,
    name: "Polo",
    slug: "polo",
    permalink: "http://wooapp.local/product/polo/",
    date_created: "2021-06-10T13:37:39",
    date_created_gmt: "2021-06-10T13:37:39",
    date_modified: "2021-06-10T13:38:12",
    date_modified_gmt: "2021-06-10T13:38:12",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>\n",
    short_description: "<p>This is a simple product.</p>\n",
    sku: "woo-polo",
    price: "20",
    regular_price: "20",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: {
      length: "",
      width: "",
      height: "",
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      {
        id: 17,
        name: "Tshirts",
        slug: "tshirts",
      },
    ],
    tags: [],
    images: [
      {
        id: 52,
        date_created: "2021-06-10T13:38:11",
        date_created_gmt: "2021-06-10T13:38:11",
        date_modified: "2021-06-10T13:38:11",
        date_modified_gmt: "2021-06-10T13:38:11",
        src: "http://wooapp.local/wp-content/uploads/2021/06/polo-2.jpg",
        name: "polo-2.jpg",
        alt: "",
      },
    ],
    attributes: [
      {
        id: 1,
        name: "Color",
        position: 0,
        visible: true,
        variation: false,
        options: ["Blue"],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>20.00</bdi></span>',
    related_ids: [32, 15, 12, 22],
    meta_data: [
      {
        id: 555,
        key: "_wpcom_is_markdown",
        value: "1",
      },
    ],
    stock_status: "instock",
    _links: {
      self: [
        {
          href: "http://wooapp.local/wp-json/wc/v3/products/23",
        },
      ],
      collection: [
        {
          href: "http://wooapp.local/wp-json/wc/v3/products",
        },
      ],
    },
  },
  {
    id: 22,
    name: "Long Sleeve Tee",
    slug: "long-sleeve-tee",
    permalink: "http://wooapp.local/product/long-sleeve-tee/",
    date_created: "2021-06-10T13:37:39",
    date_created_gmt: "2021-06-10T13:37:39",
    date_modified: "2021-06-10T13:38:10",
    date_modified_gmt: "2021-06-10T13:38:10",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>\n",
    short_description: "<p>This is a simple product.</p>\n",
    sku: "woo-long-sleeve-tee",
    price: "25",
    regular_price: "25",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: {
      length: "",
      width: "",
      height: "",
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      {
        id: 17,
        name: "Tshirts",
        slug: "tshirts",
      },
    ],
    tags: [],
    images: [
      {
        id: 51,
        date_created: "2021-06-10T13:38:10",
        date_created_gmt: "2021-06-10T13:38:10",
        date_modified: "2021-06-10T13:38:10",
        date_modified_gmt: "2021-06-10T13:38:10",
        src: "http://wooapp.local/wp-content/uploads/2021/06/long-sleeve-tee-2.jpg",
        name: "long-sleeve-tee-2.jpg",
        alt: "",
      },
    ],
    attributes: [
      {
        id: 1,
        name: "Color",
        position: 0,
        visible: true,
        variation: false,
        options: ["Green"],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>25.00</bdi></span>',
    related_ids: [32, 12, 23, 15],
    meta_data: [
      {
        id: 546,
        key: "_wpcom_is_markdown",
        value: "1",
      },
    ],
    stock_status: "instock",
    _links: {
      self: [
        {
          href: "http://wooapp.local/wp-json/wc/v3/products/22",
        },
      ],
      collection: [
        {
          href: "http://wooapp.local/wp-json/wc/v3/products",
        },
      ],
    },
  },
  {
    id: 21,
    name: "Hoodie with Zipper",
    slug: "hoodie-with-zipper",
    permalink: "http://wooapp.local/product/hoodie-with-zipper/",
    date_created: "2021-06-10T13:37:39",
    date_created_gmt: "2021-06-10T13:37:39",
    date_modified: "2021-06-10T13:38:08",
    date_modified_gmt: "2021-06-10T13:38:08",
    type: "simple",
    status: "publish",
    featured: true,
    catalog_visibility: "visible",
    description:
      "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>\n",
    short_description: "<p>This is a simple product.</p>\n",
    sku: "woo-hoodie-with-zipper",
    price: "45",
    regular_price: "45",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: {
      length: "",
      width: "",
      height: "",
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      {
        id: 18,
        name: "Hoodies",
        slug: "hoodies",
      },
    ],
    tags: [],
    images: [
      {
        id: 50,
        date_created: "2021-06-10T13:38:08",
        date_created_gmt: "2021-06-10T13:38:08",
        date_modified: "2021-06-10T13:38:08",
        date_modified_gmt: "2021-06-10T13:38:08",
        src: "http://wooapp.local/wp-content/uploads/2021/06/hoodie-with-zipper-2.jpg",
        name: "hoodie-with-zipper-2.jpg",
        alt: "",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>45.00</bdi></span>',
    related_ids: [13, 14],
    meta_data: [
      {
        id: 537,
        key: "_wpcom_is_markdown",
        value: "1",
      },
    ],
    stock_status: "instock",
    _links: {
      self: [
        {
          href: "http://wooapp.local/wp-json/wc/v3/products/21",
        },
      ],
      collection: [
        {
          href: "http://wooapp.local/wp-json/wc/v3/products",
        },
      ],
    },
  },
  {
    id: 20,
    name: "Hoodie with Pocket",
    slug: "hoodie-with-pocket",
    permalink: "http://wooapp.local/product/hoodie-with-pocket/",
    date_created: "2021-06-10T13:37:38",
    date_created_gmt: "2021-06-10T13:37:38",
    date_modified: "2021-06-10T13:38:06",
    date_modified_gmt: "2021-06-10T13:38:06",
    type: "simple",
    status: "publish",
    featured: true,
    catalog_visibility: "hidden",
    description:
      "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>\n",
    short_description: "<p>This is a simple product.</p>\n",
    sku: "woo-hoodie-with-pocket",
    price: "35",
    regular_price: "45",
    sale_price: "35",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: 0,
    download_expiry: 0,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: {
      length: "",
      width: "",
      height: "",
    },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      {
        id: 18,
        name: "Hoodies",
        slug: "hoodies",
      },
    ],
    tags: [],
    images: [
      {
        id: 49,
        date_created: "2021-06-10T13:38:05",
        date_created_gmt: "2021-06-10T13:38:05",
        date_modified: "2021-06-10T13:38:05",
        date_modified_gmt: "2021-06-10T13:38:05",
        src: "http://wooapp.local/wp-content/uploads/2021/06/hoodie-with-pocket-2.jpg",
        name: "hoodie-with-pocket-2.jpg",
        alt: "",
      },
    ],
    attributes: [
      {
        id: 1,
        name: "Color",
        position: 0,
        visible: true,
        variation: false,
        options: ["Gray"],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>45.00</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>35.00</bdi></span></ins>',
    related_ids: [13, 14, 21],
    meta_data: [
      {
        id: 526,
        key: "_wpcom_is_markdown",
        value: "1",
      },
    ],
    stock_status: "instock",
    _links: {
      self: [
        {
          href: "http://wooapp.local/wp-json/wc/v3/products/20",
        },
      ],
      collection: [
        {
          href: "http://wooapp.local/wp-json/wc/v3/products",
        },
      ],
    },
  },
];

export default products;
